In [68]:
import pandas as pd
df = pd.read_csv("train.csv")
df.values

array([[ 24,  51,  44, ...,  27,   0,   3],
       [ 22,  31, 214, ...,   0,   0,   2],
       [ 84, 126, 239, ...,  24,   8,   9],
       ...,
       [268, 358, 277, ...,  47,   7,   5],
       [ 81, 116,  90, ...,   9,   0,   2],
       [118, 156, 197, ...,   0,   0,   5]])

In [31]:
import torch
import numpy as np

np_array = np.array(df)

In [32]:
np_array

array([[ 24,  51,  44, ...,  27,   0,   3],
       [ 22,  31, 214, ...,   0,   0,   2],
       [ 84, 126, 239, ...,  24,   8,   9],
       ...,
       [268, 358, 277, ...,  47,   7,   5],
       [ 81, 116,  90, ...,   9,   0,   2],
       [118, 156, 197, ...,   0,   0,   5]])

In [34]:
df

POS_0_9_CP  POS_10_19_CP  POS_20_29_CP  POS_30_39_CP  POS_40_49_CP  \
0             24            51            44            51            60   
1             22            31           214           177            62   
2             84           126           239           194           159   
3             65            76            80           110            82   
4             99           107           339           287           139   
...          ...           ...           ...           ...           ...   
1039          86           201           206           202           240   
1040          80           102           125           124           104   
1041         268           358           277           415           355   
1042          81           116            90           145           118   
1043         118           156           197           215           114   

      POS_50_59_CP  POS_60_69_CP  POS_70_79_CP  POS_80_89_CP  POS_90_CP  \
0               75            72            61            27          0   
1               46            24             9             0          0   
2              171           125            74            24          8   
3               81            55            49            56         34   
4              147           110            71            37          0   
...            ...           ...           ...           ...        ...   
1039           317           225           138            48          0   
1040            71            70            36             6          0   
1041           332           215           107            47          7   
1042           113            70            36             9          0   
1043           114            83            19             0          0   

      DTH_CUM_CP  
0              3  
1              2  
2              9  
3              7  
4             12  
...          ...  
1039           7  
1040           6  
1041           5  
1042           2  
1043           5  

[1044 rows x 11 columns]

In [100]:
ds = torch.utils.data.TensorDataset(
    torch.tensor(df.loc[:, "POS_0_9_CP":"POS_90_CP"].values),
    torch.tensor(df.loc[:, ["DTH_CUM_CP"]].values)
)

In [331]:
trainX, trainY = ds[: :]

In [332]:
trainX = trainX.to(torch.float64)
trainY = trainY.to(torch.float64)

In [333]:
trainX

tensor([[ 24.,  51.,  44.,  ...,  61.,  27.,   0.],
        [ 22.,  31., 214.,  ...,   9.,   0.,   0.],
        [ 84., 126., 239.,  ...,  74.,  24.,   8.],
        ...,
        [268., 358., 277.,  ..., 107.,  47.,   7.],
        [ 81., 116.,  90.,  ...,  36.,   9.,   0.],
        [118., 156., 197.,  ...,  19.,   0.,   0.]], dtype=torch.float64)

In [334]:
trainY

tensor([[3.],
        [2.],
        [9.],
        ...,
        [5.],
        [2.],
        [5.]], dtype=torch.float64)

In [338]:
# Q1: about how many bytes does trainX consume?
print(trainX.nelement() * trainX.element_size())

83520


In [399]:
# Q2: what is the biggest difference we would have any one cell if we used float16 instead of float64?
biggest_val = -1.0
for cell in trainX:
    # print(cell)
    float16_X = cell.to(torch.float16)
    float16_X = float16_X.to(torch.float64)
    # print(torch.sum(float16_X))
    diff = abs(float16_X - cell)
    # torch.sum(diff)
    # print(torch.sum(diff).item())
    curr_val = torch.sum(diff).item()
    if curr_val > biggest_val:
        biggest_val = curr_val
print(biggest_val)

0.0


In [400]:
# Q3: is a CUDA GPU available on your VM?
torch.cuda.is_available()

False